---
abstract: 'Lightweight Teng'
author:
  - 'y_uuki <yuki.tsubo@gmail.com>'
build_requires:
  DBD::SQLite: 0
  Exporter::Lite: 0
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.8.0, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Coteng
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Coteng:
    file: lib/Coteng.pm
    version: 0.01
  Coteng::DBI:
    file: lib/Coteng/DBI.pm
    version: 0
  Coteng::DBI::db:
    file: lib/Coteng/DBI.pm
    version: 0
  Coteng::DBI::st:
    file: lib/Coteng/DBI.pm
    version: 0
requires:
  Class::Accessor::Lite::Lazy: 0
  DBI: 1.630
  DBIx::Sunny: 0.21
  Module::Load: 0
  SQL::Maker: 1.12
  SQL::NamedPlaceholder: 0.03
  parent: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/y-uuki/Coteng/issues
  homepage: https://github.com/y-uuki/Coteng
  repository: git://github.com/y-uuki/Coteng.git
version: 0.01
x_authority: cpan:YUUKI
